#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""DeepSeek Harness 一键安装程序 (DSH Setup).

把一个电脑小白需要的全部东西装到一台 Windows 机器上：
  0) 安装前先做环境预检 (网络 / 磁盘 / 权限 / 端口…), 结果给用户确认
  1) 解压便携版 Node.js (runtime)
  2) 复制面板 (DSHLauncher.exe) 并写入 harness.txt
  3) 用内置 npm 从官方源安装 `@deepseek-ai/dsh` 到 harness/
  4) 试运行一次, 确认装出来的东西真能起得来
  5) 创建桌面与开始菜单快捷方式、写卸载注册信息
  6) 提供 uninstall.bat 一键卸载

安装的是上游发布在 npm 上的**预编译包**（他们自己的安装方式就是
`npx @deepseek-ai/dsh web`，GitHub release 上一个资产都没有）。所以整条链路
不碰源码、不做本地构建，也就不需要任何 C++ 编译器，约一分钟装完。

`--ignore-scripts` 是刻意的：上游的包自带各平台 prebuild，不需要编译；而
node-pty 的安装脚本是 `prebuild.js || node-gyp rebuild`，一旦回退就会要求
MSVC。装完的试运行是这条选择的兜底。

启动器和 dsh 本体是分开的：harness/ 可以整个换掉，launcher/ 不受影响；
用户的设置、密钥和会话在 ~/.dsh，两者都碰不到。

用 PyInstaller onefile 打包, 安装负载内嵌在 exe 里。

命令行模式 (供构建/自检用, 不弹窗):
  DSHSetup.exe --auto [--dir <安装目录>] [--skip-preflight]
  DSHSetup.exe --diag [--dir <安装目录>]   # 只读环境报告，不安装（排障用）
  DSHSetup.exe --selfcheck
"""
from __future__ import annotations

import json
import os
import platform
import queue
import re
import shutil
import socket
import subprocess
import sys
import threading
import time
import zipfile

import tkinter as tk
from tkinter import filedialog, messagebox, ttk

import linkcheck
import preflight

try:
    # Generated by scripts/make-version-info.py from launcher.pyw's VERSION, so
    # there is exactly one place a version number lives. Absent in a source
    # checkout that has never been built.
    from _version import VERSION as SETUP_VERSION
except ImportError:  # pragma: no cover - dev checkout
    SETUP_VERSION = "unknown"

def _SYS32(name: str) -> str:
    """Absolute path to a Windows system tool.

    Bare names resolve through PATH, so a directory earlier in PATH wins — a
    trivial way to make this program execute somebody else's taskkill.exe.
    Nothing here needs that risk; the path is always the same.
    """
    root = os.environ.get("SystemRoot") or r"C:\Windows"
    return os.path.join(root, "System32", name)



def _POWERSHELL() -> str:
    """Absolute path to Windows PowerShell (it is not directly in System32)."""
    root = os.environ.get("SystemRoot") or r"C:\Windows"
    return os.path.join(root, "System32", "WindowsPowerShell", "v1.0", "powershell.exe")




APP_NAME = "DSH"
# The harness is installed from npm — upstream publishes prebuilt packages there
# and nothing at all on GitHub releases, and their own documented install is
# `npx @deepseek-ai/dsh web`. Installing the published package takes about a
# minute and needs no source checkout, no pnpm and no compiler, where the old
# source-and-build flow took 10~25 minutes and 4~5 GB.
HARNESS_NPM_NAME = "@deepseek-ai/dsh"
# Resolved at install time rather than pinned: upstream's `latest` is their own
# statement of which version a new user should get, and following it means a
# shipped DSHSetup.exe does not go stale. The smoke test below is what makes
# that safe.
HARNESS_NPM_TAG = "latest"
# Fallback for the uninstall entry before the real version is known.
APP_VERSION = "unknown"
LAUNCHER_DISPLAY = "DSH"
WEB_PORT = 3080
SINGLETON_PORT = 3199
# Written into harness\ only after npm exited 0 and the entry point was found.
# Its whole job is to make "reuse what is already on disk" safe: a bare
# package.json proves nothing, because a cancelled npm install leaves one behind
# with the right version and half the dependency tree.
MARKER_NAME = ".dsh-installed.json"


def _is_elevated() -> bool:
    """Whether this process holds an elevated admin token.

    Cheap and process-local — no subprocess like `whoami`, which under a
    security product's hooking costs a noticeable moment on every install.
    """
    try:
        import ctypes
        return bool(ctypes.windll.shell32.IsUserAnAdmin())
    except Exception:  # noqa: BLE001 - never let diagnostics break an install
        return False


def _env_facts(target: str, proxy: str | None = None) -> list[str]:
    """The machine facts worth having in any log a user sends us.

    Shared by the install log header and by `--diag`, so a report and an install
    log can never disagree about the same machine.

    Deliberately absent: SeCreateSymbolicLinkPrivilege. dsh links its profile
    fallbacks with junctions, which need no privilege at all, so printing
    "priv: no" into a block users forward to us would teach the wrong lesson —
    that is exactly the red herring this release exists to kill.
    """
    profile = os.environ.get("USERPROFILE") or ""
    try:
        ver = sys.getwindowsversion()
        os_name = "Windows %d.%d build %d %s" % (ver.major, ver.minor, ver.build,
                                                 platform.machine())
    except AttributeError:  # pragma: no cover - non-Windows
        os_name = platform.platform()
    try:
        # Walk up first: the install directory usually does not exist yet.
        free_gb = "%.1f GB free" % (shutil.disk_usage(linkcheck.existing_ancestor(target)).free
                                    / (1024.0 ** 3))
    except OSError:
        free_gb = "unknown"
    return [
        "target: %s" % target,
        "os: %s" % os_name,
        "account: %s" % (os.environ.get("USERNAME") or "?"),
        "dsh home: %s" % (os.path.join(profile, ".dsh") if profile else "?"),
        "elevated: %s" % ("yes" if _is_elevated() else "no"),
        "developer mode: %s (affects symlinks only - dsh uses junctions)"
        % ("on" if preflight.dev_mode_enabled() else "off"),
        "disk: %s" % free_gb,
        "proxy: %s" % (proxy or "none"),
        "setup exe: %s" % (sys.executable if getattr(sys, "frozen", False)
                           else os.path.abspath(__file__)),
    ]


def _say(text: str) -> None:
    """print() that cannot kill a headless run.

    stdout is None in a windowed frozen exe, and on a Chinese Windows it is
    cp936 as soon as it is redirected — one character outside that code page
    (an arrow, a check mark) would otherwise abort the install halfway through.
    """
    out = sys.stdout
    if out is None:
        return
    try:
        print(text, flush=True)
    except UnicodeEncodeError:
        enc = getattr(out, "encoding", None) or "ascii"
        out.write(text.encode(enc, "replace").decode(enc, "replace") + "\n")
        out.flush()


# --------------------------------------------------------------------------
# resource paths (frozen exe vs source checkout)
# --------------------------------------------------------------------------
def _project_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _resource_dir() -> str:
    if getattr(sys, "frozen", False):
        return getattr(sys, "_MEIPASS", os.path.dirname(sys.executable))
    return os.path.join(_project_root(), "payload")


def _resource(name: str) -> str:
    return os.path.join(_resource_dir(), name)


def resources() -> dict:
    """All payload paths, with dev-mode fallbacks into the source tree."""
    root = _project_root()
    return {
        "node_zip": _resource("node-v24.18.0-win-x64.zip"),
        "launcher_exe": _resource("DSHLauncher.exe"),
        "icon": _resource("icon.ico"),
        "make_shortcut_ps1": _resource("make-shortcut.ps1"),
        "dev_launcher_exe": os.path.join(root, "launcher", "dist", "DSHLauncher.exe"),
        "dev_icon": os.path.join(root, "launcher", "icon.ico"),
        "dev_make_shortcut_ps1": os.path.join(root, "installer", "make-shortcut.ps1"),
    }


def _pick(res: dict, key: str, dev_key: str | None = None) -> str:
    p = res[key]
    if os.path.exists(p):
        return p
    if dev_key and os.path.exists(res[dev_key]):
        return res[dev_key]
    return p


def _installed_harness_version(harness_dir: str) -> str:
    """The version npm actually put on disk."""
    pkg = os.path.join(harness_dir, "node_modules", "@deepseek-ai", "dsh", "package.json")
    try:
        with open(pkg, encoding="utf-8") as f:
            version = json.load(f).get("version")
        return version if isinstance(version, str) and version else APP_VERSION
    except (OSError, ValueError):
        return APP_VERSION


def _claim_singleton() -> bool:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        s.bind(("127.0.0.1", SINGLETON_PORT))
        s.listen(1)
        return True
    except OSError:
        return False


# --------------------------------------------------------------------------
# install worker
# --------------------------------------------------------------------------
class InstallCancelled(Exception):
    pass


class InstallWorker(threading.Thread):
    def __init__(self, target: str, res: dict, events: "queue.Queue[dict]",
                 cancel: threading.Event, test_mode: bool = False,
                 proxy: str | None = None):
        super().__init__(daemon=True)
        self.target = os.path.abspath(target)
        self.res = res
        self.events = events
        self.cancel = cancel
        self.test_mode = test_mode   # --auto: skip desktop/registry integration
        # `host:port` to route pnpm through, set by preflight when the direct
        # route is unusable but the machine's configured proxy works.
        self.proxy = proxy
        self.log_path = os.path.join(self.target, "install.log")
        self.launcher_dir = os.path.join(self.target, "launcher")
        self.harness_dir = os.path.join(self.target, "harness")
        self.runtime_dir = os.path.join(self.target, "runtime")
        # Filled in once npm tells us what it actually installed; the uninstall
        # entry is written twice — once early so a failed install stays
        # removable, once after the harness lands so the version is real.
        self.app_version = APP_VERSION
        # Result of the link-capability probe, kept so the failure diagnosis can
        # quote it. Empty means the probe never ran (e.g. it failed before the
        # runtime was extracted) — which the diagnosis must not read as FAIL.
        self.links_report: dict = {}
        # Last thing shown on the progress bar, used as "which step failed".
        self._last_progress = ""
        # Set when install.log itself cannot be written, so the failure screen
        # can say so instead of pointing at a file that does not exist.
        self.log_broken = False

    # ---- helpers ----------------------------------------------------------
    def emit(self, kind: str, **kw) -> None:
        if "msg" in kw:
            # Keep the on-screen text and the file in agreement: the log is
            # redacted in log(), so the event payload has to be too.
            kw["msg"] = linkcheck.redact(kw["msg"])
        self.events.put({"kind": kind, **kw})

    def progress(self, pct: float, text: str) -> None:
        self._last_progress = text
        self.emit("progress", pct=pct, text=text)

    def log(self, msg: str) -> None:
        # Redaction happens here, at the single point every line goes through:
        # dsh prints a one-time login URL at startup, and this file is the one
        # the README tells users to send us.
        line = time.strftime("[%H:%M:%S] ") + linkcheck.redact(msg) + "\n"
        try:
            with open(self.log_path, "a", encoding="utf-8") as f:
                f.write(line)
        except OSError:
            self.log_broken = True
            return
        if self.test_mode:
            # --auto reads the log from stdout; the GUI reads the file directly.
            self.emit("log", msg=line.rstrip("\n"))

    def _check_cancel(self) -> None:
        if self.cancel.is_set():
            raise InstallCancelled()

    def _write_env_header(self) -> None:
        """Everything about the machine, before the first byte lands.

        Gives a support reader the run separator (a retry appends to the same
        file, and yesterday's log was five runs run together), the installer's
        own version — which used to appear nowhere in the log at all — and the
        machine facts from _env_facts(). No progress() call here: the
        2/22/24/28/86/92/97/100 sequence stays exactly as it was.
        """
        self.log("=" * 72)
        self.log("run start: DSHSetup %s  %s"
                 % (SETUP_VERSION, time.strftime("%Y-%m-%d %H:%M:%S")))
        for fact in _env_facts(self.target, self.proxy):
            self.log(fact)
        self._check_cancel()

    def _diagnose(self, exc: Exception) -> None:
        """Add what actually went wrong, into the same file.

        The smoke test writes its output to smoke.log, so a support reader used
        to need two files — and had to know the second one existed. Everything
        the rule table needs is already in hand by the time we get here.
        """
        try:
            smoke_path = os.path.join(self.target, "smoke.log")
            exists = os.path.exists(smoke_path)
            smoke = ""
            if exists:
                with open(smoke_path, "rb") as f:
                    smoke = f.read().decode("utf-8", "replace")
            self.log("-- 诊断 " + "-" * 60)
            for line in linkcheck.diagnose(
                    smoke, self.links_report, error=repr(exc),
                    step=self._last_progress, target=self.target,
                    harness_version=self.app_version, smoke_exists=exists):
                self.log(line)
        except Exception:  # noqa: BLE001 - never let diagnosis hide the real error
            self.log("-- 诊断: 生成失败，看上面的错误信息")

    # ---- entry ------------------------------------------------------------
    def run(self) -> None:
        try:
            self._install()
            self.emit("done", ok=True, msg="安装完成")
        except InstallCancelled:
            self.log("安装已取消")
            self.emit("done", ok=False, msg="安装已取消")
        except Exception as exc:  # noqa: BLE001
            self._diagnose(exc)
            self.log("!! 安装失败: %r" % (exc,))
            self.emit("done", ok=False, msg="安装失败: %s" % exc)

    def _install(self) -> None:
        self.progress(2, "正在准备…")
        os.makedirs(self.target, exist_ok=True)
        self._write_env_header()

        # 1) portable node — needed before anything else, npm comes from it
        self.log("解压 Node.js -> %s" % self.runtime_dir)
        self._extract_node(_pick(self.res, "node_zip"), self.runtime_dir, 4, 22,
                           "正在解压 Node.js 运行时…")
        self._check_cancel()

        # 1b) can this machine create links at all? The runtime can answer that
        #     now — same libuv dsh will use — and the 600 MB npm install is
        #     still ahead, so this is the last cheap moment to give up.
        self._probe_links()

        # 2) launcher
        self.progress(24, "正在安装启动器…")
        os.makedirs(self.launcher_dir, exist_ok=True)
        launcher_exe = _pick(self.res, "launcher_exe", "dev_launcher_exe")
        icon = _pick(self.res, "icon", "dev_icon")
        shutil.copy2(launcher_exe, os.path.join(self.launcher_dir, "DSHLauncher.exe"))
        if os.path.exists(icon):
            shutil.copy2(icon, os.path.join(self.launcher_dir, "icon.ico"))
        with open(os.path.join(self.launcher_dir, "harness.txt"), "w", encoding="utf-8") as f:
            f.write(self.harness_dir)
        self.log("launcher installed -> %s" % self.launcher_dir)
        self._check_cancel()

        # 3) uninstaller + registry (before deps, so a failure is still removable)
        self._write_uninstaller()
        if not self.test_mode:
            self._register_uninstall()

        # 4) the harness itself, from npm
        self._install_harness()
        self._check_cancel()
        if not self.test_mode:
            self._register_uninstall()      # now with the real dsh version

        # 5) shortcuts
        if not self.test_mode:
            self.progress(97, "正在创建快捷方式…")
            self._make_shortcuts()
        self.progress(100, "完成")
        self.log("install complete: %s" % self.target)

    # ---- extraction -------------------------------------------------------
    def _extract_node(self, zip_path: str, dest: str, p0: float, p1: float, label: str) -> None:
        if not os.path.exists(zip_path):
            raise RuntimeError("缺少安装负载: %s" % zip_path)
        tmp = dest + ".tmp"
        shutil.rmtree(tmp, ignore_errors=True)
        os.makedirs(tmp, exist_ok=True)
        try:
            with zipfile.ZipFile(zip_path) as zf:
                names = zf.namelist()
                total = len(names)
                for i, name in enumerate(names):
                    self._check_cancel()
                    if i % 150 == 0:
                        self.progress(p0 + (p1 - p0) * i / max(total, 1),
                                      "%s (%d/%d)" % (label, i, total))
                    try:
                        zf.extract(name, tmp)
                    except OSError:
                        pass
            inner = [d for d in os.listdir(tmp) if os.path.isdir(os.path.join(tmp, d))]
            src = os.path.join(tmp, inner[0]) if len(inner) == 1 else tmp
            shutil.rmtree(dest, ignore_errors=True)
            shutil.move(src, dest)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
        self.progress(p1, label)

    # ---- dependencies -----------------------------------------------------
    def _node_exe(self) -> str:
        return os.path.join(self.runtime_dir, "node.exe")

    def _probe_links(self) -> None:
        """Can this machine create the links dsh needs? Last cheap moment to ask.

        dsh builds its profile module fallbacks with `symlinkSync(..., "junction")`
        — reparse points, no privilege, no elevation, no Developer Mode. A
        machine where that fails cannot run dsh no matter how the install is
        performed, and finding out here costs a second instead of the two
        minutes and 600 MB the npm install would spend first.

        A probe that could not run is never treated as a failure: UNKNOWN means
        we did not learn anything, which is not the same as learning something
        bad.
        """
        report = linkcheck.probe(self._node_exe(), self.target, cancel=self.cancel)
        self.links_report = report
        self.log(linkcheck.render(report))
        if report.get("status") == "cancelled":
            self._check_cancel()
        if report.get("status") != "ran":
            self.log("链接能力没能测出来（%s）——按未知处理，继续安装。"
                     % (report.get("reason") or "?"))
        message = linkcheck.blocking_message(report)
        if message is not None:
            raise RuntimeError(message)

    def _npm_env(self) -> dict:
        env = dict(os.environ)
        env["PATH"] = self.runtime_dir + os.pathsep + env.get("PATH", "")
        if self.proxy:
            # npm reads proxies from the environment, never from the Windows
            # "Internet Options" proxy that preflight found this in.
            url = "http://" + self.proxy
            for name in ("HTTP_PROXY", "HTTPS_PROXY", "http_proxy", "https_proxy"):
                env[name] = url
            env["NO_PROXY"] = "localhost,127.0.0.1"
            env["no_proxy"] = "localhost,127.0.0.1"
        return env

    def _run_streamed(self, cmd: list[str], cwd: str, env: dict) -> int:
        """Run `cmd`, tee its output into install.log, honour cancellation."""
        self.log("$ %s" % " ".join(cmd))
        proc = subprocess.Popen(
            cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            env=env, shell=False,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0) | getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0),
        )
        assert proc.stdout is not None
        try:
            for raw in proc.stdout:
                try:
                    self.log(raw.decode("utf-8", "replace").rstrip("\n"))
                except OSError:
                    pass
                if self.cancel.is_set():
                    subprocess.run([_SYS32("taskkill.exe"), "/PID", str(proc.pid), "/T", "/F"],
                                   capture_output=True, creationflags=0x08000000)
                    raise InstallCancelled()
        finally:
            proc.stdout.close()
        return proc.wait()

    def _npm_cli(self) -> str:
        """npm's entry script inside the portable runtime."""
        return os.path.join(self.runtime_dir, "node_modules", "npm", "bin", "npm-cli.js")

    def _install_harness(self) -> None:
        """Install `@deepseek-ai/dsh` from npm into <target>\\harness.

        `--ignore-scripts` is deliberate, not a shortcut: upstream's packages
        ship prebuilt binaries for every platform, so nothing needs compiling,
        while node-pty's install script is `prebuild.js || node-gyp rebuild` —
        letting it run risks demanding Visual Studio C++ on a machine that has
        none. The smoke test after this is what makes that bet safe.
        """
        node, npm = self._node_exe(), self._npm_cli()
        if not os.path.exists(node):
            raise RuntimeError("便携版 node.exe 缺失: %s" % node)
        if not os.path.exists(npm):
            raise RuntimeError("便携版 Node 缺少 npm: %s" % npm)
        os.makedirs(self.harness_dir, exist_ok=True)

        reused = self._reuse_harness()
        if reused is not None:
            # A retry after a failure that had nothing to do with the download
            # (a link the machine refuses to create, a backend that would not
            # start) must not pay 2 minutes and 600 MB again.
            self.progress(28, "已装好 dsh 本体 v%s，跳过下载…" % reused)
            self.log("reusing harness v%s（%s；要重装请先运行 uninstall.bat）"
                     % (reused, os.path.join(self.harness_dir, MARKER_NAME)))
        else:
            spec = "%s@%s" % (HARNESS_NPM_NAME, HARNESS_NPM_TAG)
            self.progress(28, "正在从 npm 安装 dsh 本体（约 600 MB，1~3 分钟）…")
            code = self._run_streamed(
                [node, npm, "install", "--no-audit", "--no-fund",
                 "--ignore-scripts", "--loglevel=warn", spec],
                self.harness_dir, self._npm_env())
            if code != 0:
                raise RuntimeError("dsh 安装失败 (exit %d)，详见 %s" % (code, self.log_path))
            self._check_cancel()

        entry = os.path.join(self.harness_dir, "node_modules", "@deepseek-ai", "dsh",
                             "lib", "bin.js")
        if not os.path.exists(entry):
            raise RuntimeError("装完了但找不到 %s" % entry)
        self.app_version = _installed_harness_version(self.harness_dir)
        self.log("harness installed: v%s -> %s" % (self.app_version, entry))
        self._write_install_marker()
        self._smoke_test()

    def _reuse_harness(self) -> str | None:
        """The version already on disk, if a previous run completed npm install.

        The completion marker is what makes this safe. A package.json alone
        proves nothing: cancelling npm halfway leaves one with the right version
        and half the dependency tree, and reusing that would pin a broken
        install that no retry could repair. Only MARKER_NAME — written after npm
        exited 0 *and* the entry point was found — can claim completion.

        No `npm view` freshness check on purpose: it would spend a network round
        trip to decide not to use the network, on exactly the machines whose
        network is the reason they are retrying.
        """
        try:
            with open(os.path.join(self.harness_dir, MARKER_NAME), encoding="utf-8") as f:
                marked = json.load(f).get("version")
        except (OSError, ValueError):
            return None
        if not isinstance(marked, str) or not marked or marked == APP_VERSION:
            return None
        installed = _installed_harness_version(self.harness_dir)
        if installed != marked:
            return None
        entry = os.path.join(self.harness_dir, "node_modules", "@deepseek-ai", "dsh",
                             "lib", "bin.js")
        return installed if os.path.exists(entry) else None

    def _write_install_marker(self) -> None:
        try:
            with open(os.path.join(self.harness_dir, MARKER_NAME), "w", encoding="utf-8") as f:
                json.dump({"version": self.app_version,
                           "ts": time.strftime("%Y-%m-%d %H:%M:%S")}, f)
        except OSError:
            pass

    def _smoke_test(self) -> None:
        """Start the harness once and confirm it serves before calling this done.

        Installing is not the same as running. This is also what makes
        `@latest` + `--ignore-scripts` a safe pair: a broken upstream release
        fails here, in front of the user, instead of the first time they press
        启动.
        """
        node = self._node_exe()
        entry = os.path.join(self.harness_dir, "node_modules", "@deepseek-ai", "dsh",
                             "lib", "bin.js")
        port = 3198                      # deliberately not 3080: don't fight a running install
        self.progress(86, "正在试运行…")
        log_file = os.path.join(self.target, "smoke.log")
        info = subprocess.STARTUPINFO()
        info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        try:
            log = open(log_file, "wb", buffering=0)
        except OSError:
            log = None
        try:
            proc = subprocess.Popen(
                [node, entry, "web", "--no-open", "--port", str(port)],
                cwd=self.harness_dir, stdout=log, stderr=log, startupinfo=info,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0), shell=False)
        except Exception as exc:  # noqa: BLE001
            if log is not None:
                log.close()
            raise RuntimeError("试运行启动失败: %s" % exc) from exc

        deadline = time.time() + 120
        url = ""
        try:
            while time.time() < deadline:
                self._check_cancel()
                if proc.poll() is not None:
                    raise RuntimeError("试运行时进程退出了 (exit %s)，详见 %s"
                                       % (proc.returncode, log_file))
                try:
                    with open(log_file, "rb") as f:
                        text = f.read().decode("utf-8", "replace")
                    match = re.search(r"dsh web:\s*(http://127\.0\.0\.1:\d+/\?token=[\w.\-]+)",
                                      text)
                    if match:
                        url = match.group(1)
                        break
                except OSError:
                    pass
                time.sleep(0.5)
        finally:
            subprocess.run([_SYS32("taskkill.exe"), "/PID", str(proc.pid), "/T", "/F"],
                           capture_output=True, creationflags=0x08000000)
            if log is not None:
                log.close()
        if not url:
            raise RuntimeError("试运行 120 秒内没有拿到登录令牌，详见 %s" % log_file)
        self.log("试运行通过: %s" % url)
        self.progress(92, "试运行通过")
        try:
            os.remove(log_file)
        except OSError:
            pass

    # ---- uninstaller / registry ------------------------------------------
    def _write_uninstaller(self) -> None:
        """Generate uninstall.bat (pure ASCII). cmd.exe does NOT collapse %%
        outside FOR loops, so batch-parameter expansions use a single % and
        FOR loop variables use %%; the batch deletes itself last via a
        detached process to avoid killing the running script."""
        bat = os.path.join(self.target, "uninstall.bat")
        lines = [
            "@echo off",
            "rem DSH uninstaller (generated by DSH Setup)",
            "setlocal",
            'set "DIR=%~dp0"',
            'if "%DIR:~-1%"=="\\" set "DIR=%DIR:~0,-1%"',
            "rem Refuse to run anywhere that is not a DSH install. The last",
            "rem steps remove every subdirectory of %~dp0 and then the",
            "rem directory itself, so a wrong location here is destructive.",
            'if not exist "%~dp0launcher\\DSHLauncher.exe" if not exist "%~dp0harness" if not exist "%~dp0runtime" (',
            "  echo This does not look like a DSH install directory:",
            "  echo   %~dp0",
            "  echo Nothing was deleted.",
            "  pause",
            "  exit /b 1",
            ")",
            "echo Stopping DSH and the backend...",
            "taskkill /F /IM DSHLauncher.exe >nul 2>&1",
            'for /f "tokens=5" %%%%p in (\'netstat -ano ^| findstr ":%d" ^| findstr "LISTENING"\') do taskkill /F /PID %%%%p >nul 2>&1' % WEB_PORT,
            "echo Removing shortcuts...",
            'if exist "%~dp0shortcuts.txt" for /f "usebackq delims=" %%L in ("%~dp0shortcuts.txt") do del /q "%%L" >nul 2>&1',
            'del /q "%USERPROFILE%\\Desktop\\DSH*.lnk" >nul 2>&1',
            'if defined OneDrive del /q "%OneDrive%\\Desktop\\DSH*.lnk" >nul 2>&1',
            # Both names: the Start Menu folder was "DeepSeek Harness" up to
            # 1.5.1, and leaving it behind would strand an empty folder for
            # anyone upgrading.
            'rmdir /s /q "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\DeepSeek Harness" >nul 2>&1',
            'rmdir /s /q "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\DSH" >nul 2>&1',
            "echo Removing registry entry...",
            'reg delete "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\DeepSeekHarness" /f >nul 2>&1',
            "echo Removing install directory...",
            'for /f "delims=" %%F in (\'dir /b /a-d "%~dp0"\') do if /i not "%%F"=="uninstall.bat" del /q "%~dp0%%F" >nul 2>&1',
            'for /d %%D in ("%~dp0*") do rmdir /s /q "\\\\?\\%%~fD" >nul 2>&1',
            "echo Uninstall finished.",
            "pause",
            'start "" /b cmd /c rmdir /s /q "\\\\?\\%DIR%" >nul 2>&1',
            'del "%~f0" >nul 2>&1',
        ]
        with open(bat, "w", encoding="ascii") as f:
            f.write("\r\n".join(lines) + "\r\n")
        self.log("uninstaller written -> %s" % bat)

    def _register_uninstall(self) -> None:
        key = r"HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\DeepSeekHarness"
        bat = os.path.join(self.target, "uninstall.bat")
        exe = os.path.join(self.launcher_dir, "DSHLauncher.exe")
        vals = [
            ("DisplayName", 'DSH'),
            ("DisplayVersion", self.app_version),
            ("Publisher", "DeepSeek AI"),
            ("InstallLocation", self.target),
            ("DisplayIcon", '"%s,0"' % exe),
            ("UninstallString", 'cmd.exe /c ""%s""' % bat),
        ]
        for name, val in vals:
            subprocess.run([_SYS32("reg.exe"), "add", key, "/f", "/v", name, "/d", val],
                           capture_output=True, creationflags=0x08000000)
        for name in ("NoModify", "NoRepair"):
            subprocess.run([_SYS32("reg.exe"), "add", key, "/f", "/v", name, "/t", "REG_DWORD", "/d", "1"],
                           capture_output=True, creationflags=0x08000000)

    # ---- shortcuts --------------------------------------------------------
    def _desktop_dir(self) -> str:
        try:
            out = subprocess.run(
                [_POWERSHELL(), "-NoProfile", "-Command", "[Environment]::GetFolderPath('Desktop')"],
                capture_output=True, text=True, creationflags=0x08000000, timeout=20)
            p = out.stdout.strip()
            if p and os.path.isdir(p):
                return p
        except Exception:
            pass
        return os.path.join(os.path.expanduser("~"), "Desktop")

    def _make_shortcuts(self) -> None:
        ps1 = _pick(self.res, "make_shortcut_ps1", "dev_make_shortcut_ps1")
        if not os.path.exists(ps1):
            raise RuntimeError("缺少 make-shortcut.ps1")
        exe = os.path.join(self.launcher_dir, "DSHLauncher.exe")
        # Point the shortcut at the exe's own icon: a self-update swaps the
        # exe but not a loose .ico, so an icon.ico path would go stale.
        icon = exe
        desc = "DSH：启动后端 / 打开网页 / 关闭 / 最小化到托盘"
        lnks = [
            os.path.join(self._desktop_dir(), LAUNCHER_DISPLAY + ".lnk"),
        ]
        start_menu = os.path.join(os.environ.get("APPDATA", ""), "Microsoft", "Windows",
                                  "Start Menu", "Programs", "DSH")
        try:
            os.makedirs(start_menu, exist_ok=True)
            lnks.append(os.path.join(start_menu, LAUNCHER_DISPLAY + ".lnk"))
        except OSError:
            pass
        for lnk in lnks:
            self._run_powershell_script(ps1, [
                "-LnkPath", lnk,
                "-TargetPath", exe,
                "-IconPath", icon,
                "-WorkingDirectory", self.launcher_dir,
                "-Description", desc,
            ])
        self.shortcuts = lnks
        # precise list for the uninstaller (ANSI, so cmd reads it under the
        # same locale it was written on)
        try:
            with open(os.path.join(self.target, "shortcuts.txt"), "w", encoding="mbcs") as f:
                f.write("\n".join(lnks))
        except OSError:
            pass

    def _run_powershell_script(self, script: str, args: list[str]) -> None:
        cmd = [_POWERSHELL(), "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", script] + args
        r = subprocess.run(cmd, capture_output=True, text=True,
                           creationflags=0x08000000, timeout=60)
        if r.returncode != 0:
            self.log("shortcut 失败(%d): %s" % (r.returncode, r.stderr.strip()))


# --------------------------------------------------------------------------
# CLI / auto mode (used by the build script and CI-style self-checks)
# --------------------------------------------------------------------------
def _run_auto(argv: list[str]) -> int:
    target = "."
    if "--dir" in argv:
        target = argv[argv.index("--dir") + 1]
    res = resources()

    proxy = None
    if "--skip-preflight" not in argv:
        report = preflight.run(os.path.abspath(target))
        for c in report.checks:
            _say("CHECK %-4s %-14s %s" % (c.status.upper(), c.key, c.detail))
            if c.hint:
                # The actionable half of a check used to be dropped here.
                _say("      hint: %s" % c.hint)
        _say("PREFLIGHT %s" % ("ok" if report.ok else "blocked"))
        if not report.ok:
            return 1
        proxy = report.proxy

    events: "queue.Queue[dict]" = queue.Queue()
    cancel = threading.Event()
    worker = InstallWorker(target, res, events, cancel, test_mode=True, proxy=proxy)
    worker.start()
    last_pct = 0
    while True:
        try:
            ev = events.get(timeout=0.25)
        except queue.Empty:
            # Only give up once the queue is empty *and* the worker is gone:
            # testing is_alive() first can drop the `done` event (and exit 1 on
            # a successful install) whenever the worker finishes between the two.
            if not worker.is_alive():
                return 1
            continue
        if ev["kind"] == "progress":
            pct = int(ev["pct"])
            if pct != last_pct:
                last_pct = pct
                _say("PROGRESS %3d%%  %s" % (pct, ev["text"]))
        elif ev["kind"] == "log":
            _say("  %s" % ev["msg"])
        elif ev["kind"] == "done":
            _say("DONE ok=%s msg=%s" % (ev["ok"], ev["msg"]))
            return 0 if ev["ok"] else 1


# --------------------------------------------------------------------------
# tkinter wizard
# --------------------------------------------------------------------------
class SetupUI:
    BG = "#0E1116"
    CARD = "#161B24"
    BORDER = "#222A36"
    TEXT = "#E8ECF3"
    SUBTEXT = "#8A94A8"
    ACCENT = "#4D6BFE"

    def __init__(self, res: dict) -> None:
        self.res = res
        self.root = tk.Tk()
        self.root.title("DSH 一键安装")
        self.root.configure(bg=self.BG)
        self.root.geometry("640x520")
        self.root.minsize(600, 480)
        try:
            self.root.iconbitmap(_pick(res, "icon", "dev_icon"))
        except Exception:
            pass

        self.events: "queue.Queue[dict]" = queue.Queue()
        self.worker: InstallWorker | None = None
        self.cancel = threading.Event()
        # Set by the preflight page; carries the proxy the installer should
        # hand to pnpm when only the machine's proxy route reaches npm.
        self._pf_result = None
        self.target_var = tk.StringVar(value=self._default_target())
        self.launch_var = tk.BooleanVar(value=True)
        self._log_text: tk.Text | None = None
        self._bar: ttk.Progressbar | None = None
        self._status_var = tk.StringVar(value="")

        self._frame: tk.Frame | None = None
        self._show_welcome()
        self.root.after(100, self._poll_events)

    def _default_target(self) -> str:
        base = os.environ.get("LOCALAPPDATA") or os.path.expanduser("~")
        return os.path.join(base, "DeepSeekHarness")

    # ---- page switching ---------------------------------------------------
    def _clear(self) -> None:
        if self._frame is not None:
            self._frame.destroy()

    def _card(self, parent: tk.Widget, pad: int = 14) -> tk.Frame:
        f = tk.Frame(parent, bg=self.CARD, highlightbackground=self.BORDER, highlightthickness=1)
        f.pack(fill="both", expand=True)
        return f

    def _show_welcome(self) -> None:
        self._clear()
        self._frame = tk.Frame(self.root, bg=self.BG, padx=24, pady=20)
        self._frame.pack(fill="both", expand=True)
        tk.Label(self._frame, text="DSH 一键安装",
                 bg=self.BG, fg=self.TEXT, font=("Segoe UI Semibold", 17)).pack(anchor="w")
        tk.Label(self._frame, text="本地运行的 AI Agent 框架（网页界面 http://127.0.0.1:%d）" % WEB_PORT,
                 bg=self.BG, fg=self.SUBTEXT, font=("Segoe UI", 10)).pack(anchor="w", pady=(2, 14))

        card = self._card(self._frame)
        tk.Label(card, text="安装内容：", bg=self.CARD, fg=self.ACCENT,
                 font=("Segoe UI Semibold", 10)).pack(anchor="w", padx=12, pady=(10, 4))
        for line in (
            "• dsh 本体（官方 npm 预编译包 + 内置 Node.js，无需预装 Node）",
            "• 全程不需要编译，也不需要安装任何开发工具",
            "• 桌面快捷方式「%s」（启动后端 / 打开网页 / 关闭 / 最小化到托盘）" % LAUNCHER_DISPLAY,
            "• 开始菜单快捷方式与「设置 → 应用」卸载入口",
        ):
            tk.Label(card, text=line, bg=self.CARD, fg=self.TEXT,
                     font=("Segoe UI", 10)).pack(anchor="w", padx=12)

        tk.Label(card,
                 text="点「开始安装」后会先检查网络与运行环境，通过后再询问你是否开始。\n"
                      "安装全程需要联网，约 2~5 分钟，占用约 1 GB 磁盘空间。",
                 bg=self.CARD, fg="#E8A23D", font=("Segoe UI", 9), justify="left",
                 wraplength=560).pack(anchor="w", padx=12, pady=(8, 10))

        row = tk.Frame(self._frame, bg=self.BG)
        row.pack(fill="x", pady=(16, 0))
        tk.Label(row, text="安装目录：", bg=self.BG, fg=self.TEXT, font=("Segoe UI", 10)).pack(side="left")
        ent = tk.Entry(row, textvariable=self.target_var, bg=self.CARD, fg=self.TEXT,
                       insertbackground=self.TEXT, relief="flat", font=("Consolas", 9))
        ent.pack(side="left", fill="x", expand=True, padx=8, ipady=4)
        tk.Button(row, text="浏览…", command=self._browse, bg=self.CARD, fg=self.TEXT,
                  activebackground=self.BORDER, relief="flat", cursor="hand2").pack(side="left")

        btns = tk.Frame(self._frame, bg=self.BG)
        btns.pack(fill="x", pady=(18, 0))
        tk.Button(btns, text="退出", command=self.root.destroy, bg=self.CARD, fg=self.SUBTEXT,
                  activebackground=self.BORDER, relief="flat", width=10, cursor="hand2").pack(side="left")
        tk.Button(btns, text="开始安装", command=self._begin, bg=self.ACCENT, fg="#FFFFFF",
                  activebackground="#5B7BFF", relief="flat", width=14, cursor="hand2").pack(side="right")

    def _browse(self) -> None:
        d = filedialog.askdirectory(title="选择安装目录", initialdir=self.target_var.get())
        if d:
            self.target_var.set(d)

    # ---- preflight page ---------------------------------------------------
    _PF_STYLE = {
        preflight.OK: ("#18B358", "✓"),
        preflight.WARN: ("#E8A23D", "!"),
        preflight.FAIL: ("#E03B41", "✕"),
    }

    def _show_preflight(self) -> None:
        """Show the environment report, then ask before touching the disk."""
        self._clear()
        self._frame = tk.Frame(self.root, bg=self.BG, padx=24, pady=20)
        self._frame.pack(fill="both", expand=True)
        tk.Label(self._frame, text="检查安装环境…", bg=self.BG, fg=self.TEXT,
                 font=("Segoe UI Semibold", 15)).pack(anchor="w")
        self._pf_status = tk.StringVar(value="正在检查网络连接与运行环境…")
        tk.Label(self._frame, textvariable=self._pf_status, bg=self.BG, fg=self.SUBTEXT,
                 font=("Segoe UI", 10), wraplength=560, justify="left").pack(anchor="w", pady=(4, 12))

        card = tk.Frame(self._frame, bg=self.CARD, highlightbackground=self.BORDER, highlightthickness=1)
        card.pack(fill="both", expand=True)
        self._pf_rows = tk.Frame(card, bg=self.CARD)
        self._pf_rows.pack(fill="both", expand=True, padx=12, pady=10)
        self._pf_widgets: dict = {}
        self._pf_row = 0

        btns = tk.Frame(self._frame, bg=self.BG)
        btns.pack(fill="x", pady=(16, 0))
        tk.Button(btns, text="退出", command=self.root.destroy, bg=self.CARD, fg=self.SUBTEXT,
                  activebackground=self.BORDER, relief="flat", width=10,
                  cursor="hand2").pack(side="left")
        self._pf_go = tk.Button(btns, text="开始安装", command=self._show_install, bg=self.ACCENT,
                                fg="#FFFFFF", activebackground="#5B7BFF", relief="flat",
                                width=14, cursor="hand2", state="disabled")
        self._pf_go.pack(side="right")
        self._pf_retry = tk.Button(btns, text="重新检查", command=self._show_preflight, bg=self.CARD,
                                   fg=self.TEXT, activebackground=self.BORDER, relief="flat",
                                   width=10, cursor="hand2", state="disabled")
        self._pf_retry.pack(side="right", padx=(0, 8))

        self._pf_events: "queue.Queue[tuple]" = queue.Queue()
        self._pf_result = None
        threading.Thread(target=self._run_preflight, daemon=True).start()
        self.root.after(120, self._poll_preflight)

    def _run_preflight(self) -> None:
        try:
            report = preflight.run(
                self.target_var.get().strip() or ".",
                report=lambda c: self._pf_events.put(("check", c)))
            self._pf_events.put(("done", report))
        except Exception as exc:  # noqa: BLE001
            self._pf_events.put(("error", exc))

    def _pf_add_row(self, c) -> None:
        color, mark = self._PF_STYLE.get(c.status, (self.SUBTEXT, "·"))
        # Grid row comes from its own counter, not from len(self._pf_widgets):
        # the key is registered before the hint row is laid out, so counting
        # widgets put every check on the previous check's hint row.
        row = self._pf_next_row()
        tk.Label(self._pf_rows, text=mark, bg=self.CARD, fg=color,
                 font=("Segoe UI Semibold", 11)).grid(row=row, column=0, sticky="w")
        tk.Label(self._pf_rows, text=c.label, bg=self.CARD, fg=self.TEXT, anchor="w",
                 font=("Segoe UI", 10)).grid(row=row, column=1, sticky="w", padx=(6, 10))
        tk.Label(self._pf_rows, text=c.detail, bg=self.CARD, fg=color, anchor="w",
                 font=("Segoe UI", 10)).grid(row=row, column=2, sticky="w")
        self._pf_widgets[c.key] = True
        if c.hint:
            tk.Label(self._pf_rows, text="└ " + c.hint, bg=self.CARD, fg=self.SUBTEXT, anchor="w",
                     font=("Segoe UI", 8), wraplength=520, justify="left").grid(
                         row=self._pf_next_row(), column=1, columnspan=2, sticky="w", padx=(6, 0))
        self._pf_status.set("已检查 %d 项…" % len(self._pf_widgets))

    def _pf_next_row(self) -> int:
        row = self._pf_row
        self._pf_row += 1
        return row

    def _pf_finish(self, report) -> None:
        self._pf_result = report
        self._pf_status.set(preflight.summary(report))
        self._pf_retry.config(state="normal")
        if not report.ok:
            return                              # hard stop: no override button
        self._pf_go.config(state="normal")
        if messagebox.askyesno(
                "环境检查通过",
                "环境检查通过：\n\n"
                "· 系统与磁盘空间满足要求\n"
                "· 网络可以访问依赖源 (registry.npmjs.org)\n\n"
                "安装大约需要 2~5 分钟，占用约 1 GB 磁盘空间。\n现在开始安装吗？",
                parent=self.root):
            self._show_install()

    def _poll_preflight(self) -> None:
        try:
            while True:
                kind, payload = self._pf_events.get_nowait()
                if kind == "check":
                    self._pf_add_row(payload)
                elif kind == "done":
                    self._pf_finish(payload)
                    return
                else:
                    self._pf_status.set("环境检查出错：%s" % payload)
                    self._pf_retry.config(state="normal")
                    return
        except queue.Empty:
            pass
        self.root.after(120, self._poll_preflight)

    def _show_install(self) -> None:
        self._clear()
        self._frame = tk.Frame(self.root, bg=self.BG, padx=24, pady=20)
        self._frame.pack(fill="both", expand=True)
        tk.Label(self._frame, text="正在安装…", bg=self.BG, fg=self.TEXT,
                 font=("Segoe UI Semibold", 15)).pack(anchor="w")
        tk.Label(self._frame, textvariable=self._status_var, bg=self.BG, fg=self.SUBTEXT,
                 font=("Segoe UI", 10), wraplength=560, justify="left").pack(anchor="w", pady=(4, 12))
        self._bar = ttk.Progressbar(self._frame, maximum=100, value=0)
        self._bar.pack(fill="x")
        logwrap = tk.Frame(self._frame, bg=self.CARD, highlightbackground=self.BORDER, highlightthickness=1)
        logwrap.pack(fill="both", expand=True, pady=(14, 0))
        self._log_text = tk.Text(logwrap, bg=self.CARD, fg="#B7C2D4", relief="flat",
                                 font=("Consolas", 8), wrap="none", state="disabled",
                                 highlightthickness=0, borderwidth=0)
        sb = ttk.Scrollbar(logwrap, orient="vertical", command=self._log_text.yview)
        self._log_text.configure(yscrollcommand=sb.set)
        sb.pack(side="right", fill="y")
        self._log_text.pack(side="left", fill="both", expand=True, padx=(8, 0), pady=8)
        self._cancel_btn = tk.Button(self._frame, text="取消", command=self._cancel_click,
                                     bg=self.CARD, fg=self.SUBTEXT, activebackground=self.BORDER,
                                     relief="flat", width=10, cursor="hand2")
        self._cancel_btn.pack(anchor="e", pady=(12, 0))

        # start the worker
        self.cancel.clear()
        self._worker = InstallWorker(self.target_var.get(), self.res, self.events, self.cancel,
                                     proxy=self._pf_result.proxy if self._pf_result else None)
        self._worker.start()
        self.root.after(300, self._poll_log)

    def _show_done(self, ok: bool, msg: str) -> None:
        self._clear()
        self._frame = tk.Frame(self.root, bg=self.BG, padx=24, pady=20)
        self._frame.pack(fill="both", expand=True)
        color = "#18B358" if ok else "#E03B41"
        tk.Label(self._frame, text=("安装完成 🎉" if ok else "安装未完成"),
                 bg=self.BG, fg=color, font=("Segoe UI Semibold", 17)).pack(anchor="w")
        tk.Label(self._frame, text=msg, bg=self.BG, fg=self.TEXT,
                 font=("Segoe UI", 10), wraplength=560, justify="left").pack(anchor="w", pady=(6, 10))
        if ok:
            tk.Checkbutton(self._frame, text="立即启动「%s」（自动运行后端并驻留系统托盘）" % LAUNCHER_DISPLAY,
                           variable=self.launch_var, bg=self.BG, fg=self.TEXT,
                           activebackground=self.BG, selectcolor=self.CARD,
                           font=("Segoe UI", 10), cursor="hand2").pack(anchor="w")
            tk.Label(self._frame,
                     text="提示：首次打开网页后，请到「设置 → 模型」填入你的 DeepSeek API Key。\n"
                          "关闭窗口不会停止后端；点启动器里的「关闭」或运行 uninstall.bat 可彻底停止。",
                     bg=self.BG, fg=self.SUBTEXT, font=("Segoe UI", 9), justify="left",
                     wraplength=560).pack(anchor="w", pady=(10, 0))
        else:
            note = "安装日志：%s" % self._worker.log_path if self._worker else msg
            if self._worker is not None and self._worker.log_broken:
                # Pointing at a log that could not be written is how a support
                # request dies: say so instead.
                note += "\n（但这个日志没能写进去：目录不可写。换一个安装目录再试。）"
            tk.Label(self._frame, text=note, bg=self.BG, fg=self.SUBTEXT,
                     font=("Segoe UI", 9), wraplength=560,
                     justify="left").pack(anchor="w")
        btns = tk.Frame(self._frame, bg=self.BG)
        btns.pack(fill="x", pady=(18, 0))
        tk.Button(btns, text="退出", command=self.root.destroy, bg=self.CARD, fg=self.SUBTEXT,
                  activebackground=self.BORDER, relief="flat", width=10, cursor="hand2").pack(side="left")
        if ok:
            tk.Button(btns, text="完成", command=self._finish, bg=self.ACCENT, fg="#FFFFFF",
                      activebackground="#5B7BFF", relief="flat", width=14, cursor="hand2").pack(side="right")
        else:
            tk.Button(btns, text="重试", command=self._show_install, bg=self.ACCENT, fg="#FFFFFF",
                      activebackground="#5B7BFF", relief="flat", width=14, cursor="hand2").pack(side="right")

    # ---- actions ----------------------------------------------------------
    def _begin(self) -> None:
        target = self.target_var.get().strip()
        if not target:
            messagebox.showwarning("提示", "请选择安装目录", parent=self.root)
            return
        if os.path.isdir(target) and os.listdir(target):
            if not messagebox.askyesno("提示", "目录已存在且不为空：\n%s\n\n将覆盖安装（已存在的文件会被覆盖），继续吗？" % target,
                                       parent=self.root):
                return
        self._show_preflight()

    def _cancel_click(self) -> None:
        if self._worker is not None and self._worker.is_alive():
            if messagebox.askyesno("取消", "确定要取消安装吗？", parent=self.root):
                self.cancel.set()
                self._cancel_btn.config(state="disabled", text="正在取消…")

    def _finish(self) -> None:
        if self.launch_var.get() and self._worker is not None:
            exe = os.path.join(self._worker.launcher_dir, "DSHLauncher.exe")
            if os.path.exists(exe):
                try:
                    subprocess.Popen([exe], cwd=self._worker.launcher_dir,
                                     creationflags=0x08000000)
                except Exception:
                    pass
        self.root.destroy()

    # ---- event / log polling ----------------------------------------------
    def _poll_events(self) -> None:
        try:
            while True:
                ev = self.events.get_nowait()
                if ev["kind"] == "progress":
                    self._status_var.set(ev["text"])
                    if self._bar is not None:
                        self._bar["value"] = ev["pct"]
                elif ev["kind"] == "done":
                    self._show_done(ev["ok"], ev["msg"])
                    return
        except queue.Empty:
            pass
        self.root.after(100, self._poll_events)

    def _poll_log(self) -> None:
        if self._log_text is None or self._worker is None:
            return
        path = self._worker.log_path
        try:
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8", errors="replace") as f:
                    data = f.read()
                self._log_text.config(state="normal")
                self._log_text.delete("1.0", "end")
                self._log_text.insert("end", data)
                self._log_text.see("end")
                self._log_text.config(state="disabled")
        except OSError:
            pass
        self.root.after(400, self._poll_log)


def _run_diag(argv: list[str]) -> int:
    """Read-only environment report: `DSHSetup.exe --diag [--dir <target>]`.

    For the machine that will not install. Writes `diag-<timestamp>.txt` beside
    install.log when the target exists, else into %TEMP%, and echoes it. It
    never touches the install: no extraction, no harness, no registry, and the
    target directory does not have to exist.
    """
    target = "."
    if "--dir" in argv:
        target = argv[argv.index("--dir") + 1]
    target = os.path.abspath(target)

    lines: list[str] = ["DSHSetup %s  diagnostic report" % SETUP_VERSION,
                        "time: %s" % time.strftime("%Y-%m-%d %H:%M:%S"), "",
                        "== environment =="]
    lines.extend(_env_facts(target))
    lines.append("")

    lines.append("== link capability ==")
    node = os.path.join(target, "runtime", "node.exe")
    if os.path.exists(node):
        lines.append(linkcheck.render(linkcheck.probe(node, target)))
    else:
        lines.append("runtime\\node.exe 不在这里，只能做一次 OS 级检查（不含 node 自己的路）：")
        lines.append("mklink-j=%s" % linkcheck.probe_mklink_only(target))
        lines.append("（node 级判据要等 runtime 就位；上面这行只是参考。）")
    lines.append("")

    lines.append("== preflight ==")
    try:
        pf = preflight.run(target)
        for c in pf.checks:
            lines.append("%-4s %-14s %s" % (c.status.upper(), c.key, c.detail))
            if c.hint:
                lines.append("     hint: %s" % c.hint)
        lines.append("PREFLIGHT %s" % ("ok" if pf.ok else "blocked"))
    except Exception as exc:  # noqa: BLE001 - a report is still worth having
        lines.append("preflight failed: %s" % exc)
    lines.append("")

    for name in ("install.log", "smoke.log"):
        p = os.path.join(target, name)
        if not os.path.exists(p):
            continue
        lines.append("== %s（最后 25 行）==" % name)
        try:
            with open(p, "rb") as f:
                body = f.read().decode("utf-8", "replace").splitlines()
            lines.extend(body[-25:])
        except OSError as exc:
            lines.append("读不到: %s" % exc)
        lines.append("")

    text = linkcheck.redact("\n".join(lines)) + "\n"
    out_dir = target if os.path.isdir(target) else (os.environ.get("TEMP") or ".")
    path = os.path.join(out_dir, "diag-%s.txt" % time.strftime("%Y%m%d-%H%M%S"))
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
    except OSError as exc:
        path = ""
        _say("cannot write the report: %s" % exc)
    _say(text)
    if path:
        _say("report written to: %s" % path)
        if sys.stdout is None:
            # Windowed exe: the file is the only way to tell the user anything.
            try:
                messagebox.showinfo(APP_NAME, "诊断报告已保存到：\n%s\n\n请把这个文件发给我们。" % path)
            except Exception:  # noqa: BLE001
                pass
    return 0


def _run_selfcheck() -> int:
    """Headless check that every payload resource made it into the frozen exe.
    Writes selfcheck.json next to the exe (a windowed exe has no stdout)."""
    import json
    res = resources()
    rep: dict = {"frozen": bool(getattr(sys, "frozen", False)), "resources": {}}
    checks = {
        "node_zip": _pick(res, "node_zip"),
        "launcher_exe": _pick(res, "launcher_exe", "dev_launcher_exe"),
        "icon": _pick(res, "icon", "dev_icon"),
        "make_shortcut_ps1": _pick(res, "make_shortcut_ps1", "dev_make_shortcut_ps1"),
    }
    for key, p in checks.items():
        rep["resources"][key] = {
            "exists": os.path.exists(p),
            "mb": round(os.path.getsize(p) / 1048576.0, 1) if os.path.exists(p) else 0,
        }
    ok = all(rep["resources"][k]["exists"] for k in checks)
    rep["ok"] = ok
    out = os.path.join(os.path.dirname(sys.executable) if getattr(sys, "frozen", False) else ".",
                       "selfcheck.json")
    try:
        with open(out, "w", encoding="utf-8") as f:
            json.dump(rep, f, indent=2, ensure_ascii=False)
    except OSError:
        pass
    return 0 if ok else 1


def main() -> int:
    # Diagnostics run before the singleton claim on purpose: the machine that
    # needs diagnosing is often the one where an installer is already running,
    # and a refusal here is an invisible modal box in a windowless exe.
    if "--diag" in sys.argv:
        return _run_diag(sys.argv)
    if not _claim_singleton():
        messagebox.showwarning(APP_NAME, "安装程序已在运行。")
        return 1
    res = resources()
    if "--selfcheck" in sys.argv:
        return _run_selfcheck()
    if "--auto" in sys.argv:
        return _run_auto(sys.argv)
    SetupUI(res).root.mainloop()
    return 0


if __name__ == "__main__":
    sys.exit(main())
